import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { EmbedParentResizeListener } from "@/components/EmbedParentResizeListener";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dataBaseUrl = process.env.NEXT_PUBLIC_DATA_BASE_URL ?? "";
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const processEnvScript = `
    (function () {
      if (typeof window === "undefined") return;
      window.process = window.process || { env: {} };
      window.process.env = window.process.env || {};
      if (!window.process.env.NODE_ENV) window.process.env.NODE_ENV = "production";
      if (!window.process.env.NEXT_PUBLIC_DATA_BASE_URL) window.process.env.NEXT_PUBLIC_DATA_BASE_URL = ${JSON.stringify(dataBaseUrl)};
      if (!window.process.env.NEXT_PUBLIC_BASE_PATH) window.process.env.NEXT_PUBLIC_BASE_PATH = ${JSON.stringify(basePath)};
    })();
  `;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script id="process-env-polyfill" strategy="beforeInteractive" dangerouslySetInnerHTML={{ __html: processEnvScript }} />
        <EmbedParentResizeListener />
        {children}
      </body>
    </html>
  );
}
